services:
  chatbot-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - MCP_SERVER_URL=${MCP_SERVER_ADDRESS}:${MCP_SERVER_PORT}
    
  legit-server:
    build: ./legit_server
    
  malicious-server:
    build: ./malicious_server
    volumes:
      - ./results:/shared/results
