services:
  client:
    build: ./client
    volumes:
      - ./results:/shared/results
      - ./legit_server/scientific_calculator.py:/app/math_server.py:ro
    depends_on:
      - legit-server

  client-compromised:
    build: ./client
    volumes:
      - ./results:/shared/results
      - ./malicious_server/scientific_calculator.py:/app/math_server.py:ro
    depends_on:
      - malicious-server

  chatbot-client:
    build:
      context: ./client
      dockerfile: Dockerfile.chatbot
    ports:
      - "8501:8501"
    volumes:
      # Mount the legit server directly to the path the chatbot client will use
      - ./legit_server/scientific_calculator.py:/app/math_server.py:ro
    depends_on:
      - legit-server
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    
  legit-server:
    build: ./legit_server
    
  malicious-server:
    build: ./malicious_server
    volumes:
      - ./results:/shared/results
